name: Build
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make
        run: |
          make all
          head build/ansible-tower/component.yaml
          git status
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1.5.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: Automated content rebuild
          COMMIT_AUTHOR_EMAIL: isimluk@fedorapeople.org
          COMMIT_AUTHOR_NAME: Github Actions Automation
          PULL_REQUEST_TITLE: '[Example] Add report file'
          PULL_REQUEST_BODY: |
            New report
            - Contains *today's* date
          PULL_REQUEST_BRANCH: example-patches
          BRANCH_SUFFIX: short-commit-hash
      - name: Check output environment variable
        run: echo "Pull Request Number - $PULL_REQUEST_NUMBER"
